# This is a basic workflow to help you get started with Actions

name: Build Android APK with Expo

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "develop" branch
  push:
    tags:
      - "expo-v*.*.*"
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      runsOn:
        description: "Choose GitHub runner"
        required: true
        type: choice
        default: ubuntu-latest
        options:
          - ubuntu-latest
          - macos-latest
      environment:
        description: "Select the environment"
        type: environment
        required: true

permissions:
  contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment || 'development' }}
    env:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
      EXPO_PUBLIC_API_URL: ${{ secrets.EXPO_PUBLIC_API_URL }}
      IMGBB_URL: ${{ secrets.IMGBB_URL }}
      IMGBB_API_KEY: ${{ secrets.IMGBB_API_KEY }}
    defaults:
      run:
        working-directory: ./e-commerce

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Check the actual runner OS
      - name: Show actual runner OS
        run: echo "ACTUAL RUNNER OS '${{ runner.os }}'"

      # Check environment variables
      - name: Check environment variables
        run: |
          echo "ENVIRONMENT: ${{ vars.ENVIRONMENT }}"

      # Set up Node.js and install dependencies
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: ./e-commerce/package-lock.json

      - name: install app
        run: npm install --immutable --immutable-cache --check-cache

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      # Set environment variables
      - name: Create .env file
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_EXPO_PUBLIC_API_URL: ${{ vars.EXPO_PUBLIC_API_URL }}
          envkey_IMGBB_URL: ${{ vars.IMGBB_URL }}
          envkey_IMGBB_API_KEY: ${{ vars.IMGBB_API_KEY }}
          directory: ./e-commerce
          file_name: .env

      # Run the build and tests
      - name: Run Tests
        run: npm test

      # Setup Expo and EAS with EXPO_TOKEN secret
      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Build Android app
        run: eas build --platform android --profile production --local --output ${{ github.workspace }}/e-commerce.apk

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: expo-apk
          path: ${{ github.workspace }}/e-commerce.apk

  release:
    needs: build
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Download Expo APK
        uses: actions/download-artifact@v4
        with:
          name: expo-apk
          path: dist

      # Generate release notes and create a GitHub release
      - name: Generate CHANGELOG
        run: |
          # echo "# Release Notes for E-commerce Expo ${{ github.ref_name }}" > dist/CHANGELOG.md
          echo "- The Expo APK of E-commerce" >> dist/CHANGELOG.md

      - name: Create GitHub Release with APK
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*.apk"
          tag: ${{ github.ref_name }}
          bodyFile: dist/CHANGELOG.md
